"""
Centralized Application Constants
---------------------------------
Maintains all call stages, crops, and system constants.
"""


class CallStage:
    WELCOME = "WELCOME"
    LANGUAGE_SELECTED = "LANGUAGE_SELECTED"
    RECORDING_STARTED = "RECORDING_STARTED"
    RECORDING_COMPLETED = "RECORDING_COMPLETED"
    TRANSCRIBING = "TRANSCRIBING"
    TRANSCRIPTION_COMPLETED = "TRANSCRIPTION_COMPLETED"
    ROOT_CAUSE_ANALYSIS = "ROOT_CAUSE_ANALYSIS"
    AI_RESPONSE_GENERATED = "AI_RESPONSE_GENERATED"
    VOICE_RESPONSE = "VOICE_RESPONSE"
    CALL_COMPLETED = "CALL_COMPLETED"